language: go
go:
  - "1.x"
branches:
  only:
    - /^ci-.*/
    - /^v\d+/
    - master
    - stage
dist: bionic
addons:
  apt:
    packages:
      - rabbitmq-server
env:
  - AMQP_URL=amqp://guest:guest@localhost:5672/
script:
  - go test -v -tags amqp ./...
